"""initial

Revision ID: 115a1b8f440a
Revises: 
Create Date: 2026-05-21 12:14:43.455664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '115a1b8f440a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('TOILET', 'REVIEW', 'USER', name='report_target_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('FAKE', 'INAPPROPRIATE', 'SPAM', 'OUTDATED', 'OTHER', name='report_reason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'REJECTED', name='report_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_status', 'reports', ['status'], unique=False)
    op.create_table('toilets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('floor', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location_hint', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'UNISEX', 'FAMILY', name='gender'), nullable=False),
    sa.Column('toilet_type', sa.Enum('INDOOR', 'OUTDOOR', 'PORTABLE', name='toilet_type'), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('has_water', sa.Boolean(), nullable=False),
    sa.Column('has_hot_water', sa.Boolean(), nullable=False),
    sa.Column('has_soap', sa.Boolean(), nullable=False),
    sa.Column('has_dryer', sa.Boolean(), nullable=False),
    sa.Column('paper_type', sa.Enum('UNKNOWN', 'NONE', 'IN_CABIN', 'DISPENSER', 'BOTH', name='paper_type'), nullable=False),
    sa.Column('has_child_toilet', sa.Boolean(), nullable=False),
    sa.Column('has_changing_table', sa.Boolean(), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), nullable=False),
    sa.Column('cabin_count', sa.Integer(), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_toilets_created_at', 'toilets', ['created_at'], unique=False)
    op.create_index('idx_toilets_created_by', 'toilets', ['created_by'], unique=False)
    op.create_index('idx_toilets_gender', 'toilets', ['gender'], unique=False)
    op.create_index('idx_toilets_is_deleted', 'toilets', ['is_deleted'], unique=False)
    op.create_index('idx_toilets_is_verified', 'toilets', ['is_verified'], unique=False)
    op.create_index('idx_toilets_toilet_type', 'toilets', ['toilet_type'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toilet_id', 'user_id', name='uniq_confirmation_toilet_user')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('toilet_id', 'user_id', name='uniq_review_toilet_user')
    )
    op.create_index('idx_reviews_toilet_id', 'reviews', ['toilet_id'], unique=False)
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_table('toilet_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('toilet_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['toilet_id'], ['toilets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_photos')
    op.drop_table('toilet_photos')
    op.drop_index('idx_reviews_user_id', table_name='reviews')
    op.drop_index('idx_reviews_toilet_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('confirmations')
    op.drop_index('idx_toilets_toilet_type', table_name='toilets')
    op.drop_index('idx_toilets_is_verified', table_name='toilets')
    op.drop_index('idx_toilets_is_deleted', table_name='toilets')
    op.drop_index('idx_toilets_geom', table_name='toilets', postgresql_using='gist')
    op.drop_index('idx_toilets_gender', table_name='toilets')
    op.drop_index('idx_toilets_created_by', table_name='toilets')
    op.drop_index('idx_toilets_created_at', table_name='toilets')
    op.drop_table('toilets')
    op.drop_index('idx_reports_status', table_name='reports')
    op.drop_table('reports')
    op.drop_table('users')
    # ### end Alembic commands ###
